// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezrblyzzsiwwhwlffdzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cmJseXp6c2l3d2h3bGZmZHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzAxMTYsImV4cCI6MjA3MjEwNjExNn0.3kex9MA8iqnG9e-JWC6mG6OfibOKldSecNY3QPeFTho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});